- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: Get database IP address with hostvars for app servers
  hosts: appdbs
  gather_facts: true
  tag: apps
  tasks: []

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: true
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, flask]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
