---

# tasks file for osp.servers
- name: Create server instances
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    image: "{{ item.image | default('rhel-guest') }}"
    flavor: "{{ item.flavor | default('m1.medium') }}"
    key_name: "{{ item.key_name | default('ansible_ssh') }}"
    wait: yes
    security_groups: "{{ item.security_group }}"
    meta: "group={{ item.group }},deployment_name={{ item.deployment_name }}"
    nics:
      - net-name: int_network
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ osp_servers }}"

- name: Add floating IP to instances
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 180
  loop: "{{ osp_servers }}"
