---
- name: install {{ web_server }}
  yum:
    name: "{{ web_server }}"
    state: latest

- name: enable {{ web_server }} at boot
  service:
    name: "{{ web_server }}"
    enabled: yes

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644

- name: Start {{ web_server }}
  service:
    name: "{{ web_server }}"
    state: started
